apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "5000"
  MONGODB_URI: "mongodb+srv://shakshi:majorproject2026@cluster0.qtmbjuo.mongodb.net/?appName=Cluster0"
  STRIPE_SECRET_KEY: "sk_test_dummy"
  JWT_SECRET: "abc123"
  CLOUDINARY_NAME: "djk3uccjc"
  CLOUDINARY_API_KEY: "676781697896219"
  CLOUDINARY_SECRET_KEY: "Q2kQb3lPLJSQPxcSTalE7cGM1NE"
  ADMIN_EMAIL: "admin@forever.com"
  ADMIN_PASSWORD: "admin123"